Website/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using DS_SiteData;

namespace Website.Controllers
{
    public class LeftNavItem
    {
        public int Level { get; set; }
        public string Href { get; set; }
        public string DisplayText { get; set; }
    }

    public class NavigationController : Controller
    {
        //
        // GET: /Nav/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LeftNav(string CurrentLocation)
        {
            using (DS_SiteDataDbContext context = new DS_SiteDataDbContext())
            {
                List<LeftNavItem> NavItems = context
                    .ProductGroups.AsNoTracking()
                    .Where(x => x.WctKey.Contains("PF"))
                    .OrderBy(x => x.ListPosition)
                    .Select(x => new LeftNavItem{
                        Level = 0,
                        Href = "/ProductCenter/" + x.UrlKey,
                        DisplayText = x.Name
                    })
                    .ToList();

                return PartialView("_LeftNav", NavItems);
            }

        }

    }
}

Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)

            <section class="content-wrapper main-content clear-fix">

                @Html.Action("LeftNav", "Navigation")

                <div class="mainContent">
                    @RenderBody()
                </div>

            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

Website/Views/Shared/_LeftNav.cshtml
@using Website.Controllers

@model List<LeftNavItem>


<div class="leftNav">
    @foreach (var item in @Model)
    {
        <a href="@item.Href">@Html.Raw(item.DisplayText)</a><br />
    }
</div>