Website/Controllers/ProductCenterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Utilities;
using DS_SiteData;



namespace Website.Controllers
{
    public class ProductCenterController : Controller
    {

        public ActionResult Index()
        {
            using(DS_SiteDataDbContext context = new DS_SiteDataDbContext()){
                List<ProductGroup> productGroups = context
                    .ProductGroups.AsNoTracking()
                    .Where(x=> x.WctKey.Contains("PF"))
                    .OrderBy(x=>x.ListPosition)
                    .ToList();

                ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";
                return View(productGroups);
            }
        }


        public ActionResult ProductDetail(string productId)
        {

            using (DS_SiteDataDbContext context = new DS_SiteDataDbContext())
            {

                Product prodToDisplay = context.Products.AsNoTracking().Include("ProductInsert").Where(x => x.CatalogNumber == productId).First();

                ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";
                return View(prodToDisplay);
            }
        }

        public ActionResult ProductGroup(string groupId)
        {

            using (DS_SiteDataDbContext context = new DS_SiteDataDbContext())
            {
                ProductGroup productGroup = context
                    .ProductGroups.AsNoTracking()
                    .Include("Children")
                    .Include("GroupProducts")
                    .Where(x => x.UrlKey == groupId)
                    .First();

                ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";
                return View(productGroup);
            }

        }

    }
}

Website/Views/ProductCenter/Index.cshtml
@using DS_SiteData

@model List<ProductGroup>

@{
    ViewBag.Title = "Product Center";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>

<div style="position:relative; overflow:auto;">

</div>

<div class="groupListContainer">
    <div class="listCtrl">
        @foreach (var family in @Model)
        {
            <div class="Item">
                <div style="position:relative; overflow:auto;">
                    <div class="prodName">@Html.ActionLink(family.Name, family.UrlKey, "ProductCenter")</div>
                    <div class="prodNumber">@Html.Raw(family.WctKey)</div>
                </div>
                <div class="prodDescription"><p>@Html.Raw(family.LongDescription)</p></div>
            </div>
        }

        
    </div>
</div>

Website/Views/ProductCenter/ProductDetail.cshtml
@using DS_SiteData

@model Product

@{
    ViewBag.Title = "Product Details";
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>

<div class="productDetails">

    <div class="Item">
        
        <div class="tableHeader">
            <div class="columnProdNum">Catalog #</div>
            <div class="columnProdName">Description</div>
            <div class="columnProdUnit">Quantity</div>
            <div class="columnProdQuantity">Unit</div>
        </div>
        <div class="tableData">
            <div class="columnProdNum">@Html.Raw(Model.CatalogNumber)</div>
            <div class="columnProdName">@Html.Raw(Model.Name)</div>
            <div class="columnProdQuantity">@Html.Raw(Model.Quantity)</div>
            <div class="columnProdUnit">@Html.Raw(Model.Unit)</div>
        </div>

        @if (Model.ProductInsert != null)
        {
            <div style="position:relative; overflow:auto;">
                @if (Model.ProductInsert.IntendedUse.Length > 0)
                {
                    <div class="prodHeading">Intended Use</div>
                    <div class="prodDescription"><p>@Html.Raw(Model.ProductInsert.IntendedUse)</p></div>
                }
                @if (Model.ProductInsert.Summary.Length > 0)
                {
                    <div class="prodHeading">Summary and Explanation</div>
                    <div class="prodDescription"><p>@Html.Raw(Model.ProductInsert.Summary)</p></div>
                }
                @if (Model.ProductInsert.Reagents.Length > 0)
                {
                    <div class="prodHeading">Reagents</div>
                    <div class="prodDescription"><p>@Html.Raw(Model.ProductInsert.Reagents)</p></div>
                }
                @if (Model.ProductInsert.Warnings.Length > 0)
                {
                    <div class="prodHeading">Warnings and Precautions</div>
                    <div class="prodDescription"><p>@Html.Raw(Model.ProductInsert.Warnings)</p></div>
                }
            </div>
        }
    </div>

</div>

Website/Views/ProductCenter/ProductGroup.cshtml
@using DS_SiteData

@model ProductGroup

@{
    ViewBag.Title = "Product Center";
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>



<div class="groupDetails">

    <div class="Item">
        <div style="position:relative; overflow:auto;">
            <div class="prodName">@Html.Raw(Model.Name)</div>
            <div class="prodNumber">@Html.Raw(Model.WctKey)</div>
        </div>

        @if (Model.LongDescription.Length > 0)
        {
            <div style="position:relative; overflow:auto;">
                <div class="prodDescription"><p>@Html.Raw(Model.LongDescription)</p></div>
            </div>
        }
    </div>



@*<div style="position:relative; overflow:auto;">
    <h1>@Html.Raw(Model.Name)</h1>
    <p>@Html.Raw(Model.LongDescription)</p>
</div>
*@


@if(@Model.Children.Count > 0){
    Html.RenderPartial("_GroupList", Model.Children.ToList().OrderBy(a => a.ListPosition).ToList());
}

@if(Model.GroupProducts.Count > 0){
    Html.RenderPartial("_ProductList", Model.GroupProducts.ToList().OrderBy(a => a.CatalogNumber).ToList());
}

 

Website/Views/ProductCenter/_GroupList.cshtml
@using DS_SiteData

@model List<ProductGroup>

    <div class="groupListContainer">
    <div class="listCtrl">
        @foreach (var item in Model)
        {
            <div class="Item">
                <div style="position:relative; overflow:auto;">
                    <div class="prodName"><a href="@Url.Action(item.UrlKey, "ProductCenter")">@Html.Raw(item.Name)</a></div>
                    <div class="prodNumber">@Html.Raw(item.WctKey)</div>
                </div>
                <div class="prodDescription"><p>@Html.Raw(item.ShortDesciption)</p></div>
            </div>
        }
    </div>
</div>

Website/Views/ProductCenter/_ProductList.cshtml
@using DS_SiteData

@model List<Product>

<div class="prodListContainer">

        <div class="tableHeader">
            <div class="columnProdNum">Catalog #</div>
            <div class="columnProdName">Description</div>
            <div class="columnProdUnit">Quantity</div>
            <div class="columnProdQuantity">Unit</div>
        </div>

    <div class="listCtrl">
        @foreach (var item in @Model)
        {
            <div class="tableData">
                <div class="columnProdNum"><a href="@Url.Action(item.CatalogNumber, "ProductCenter")">@Html.Raw(item.CatalogNumber)</a></div>
                <div class="columnProdName"><a href="@Url.Action(item.CatalogNumber, "ProductCenter")">@Html.Raw(item.Name)</a></div>
                <div class="columnProdQuantity">@Html.Raw(item.Quantity)</div>
                <div class="columnProdUnit">@Html.Raw(item.Unit)</div>
            </div>
        }
    </div>
</div>